/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface Label;
interface nsIDOMWindow;

[scriptable, uuid(d7adf267-32de-4c03-b5e6-74d4fe21b225)]
interface nsISandboxService : nsISupports
{
  /**
   * Set to true when the document label is set.
   */
  attribute boolean isInitialized;

  /**
   * Parse a label.
   */
  boolean init(in nsIDOMWindow aWin, in AString jsonLabel);
};
